#!/bin/bash
# FILE: modules/installer.sh
# FILE: modules/installer V1.5 (SECURE UPDATE) INSTALLER=1.5

# --- [1] FUNGSI CEK PAKET & INSTALL ---
cek_paket() {
    local pkg_name=$1
    local cmd_check=$2
    
    if ! command -v "$cmd_check" &> /dev/null; then
        echo -e "\e[1;33m[*] Menginstall paket: $pkg_name...\e[0m"
        pkg install "$pkg_name" -y
    fi
}

install_kebutuhan() {
    # Pastikan folder tools ada
    if [ ! -d "$TOOLS_DIR" ]; then mkdir -p "$TOOLS_DIR"; fi

    # Update Repo Termux dulu agar tidak 404
    # echo -e "\e[1;34m[*] Memeriksa Repository Termux...\e[0m"
    # pkg update -y && pkg upgrade -y

    # Install Paket Utama
    cek_paket "bc" "bc"
    cek_paket "aria2" "aria2c"
    cek_paket "ffmpeg" "ffmpeg"
    cek_paket "termux-api" "termux-media-scan"
    cek_paket "jq" "jq"
    cek_paket "curl" "curl"
    cek_paket "figlet" "figlet"
    cek_paket "ruby" "ruby"
    cek_paket "git" "git"
    cek_paket "dos2unix" "dos2unix"
    cek_paket "python" "python"
    cek_paket "nodejs-lts" "node"
	cek_paket "xxd" "xxd"
    
    # [FIX] Install coreutils agar support command 'timeout' di viral_downloader
    cek_paket "coreutils" "timeout"
    
    # Install Gem Colors
    if ! gem list -i lolcat &> /dev/null; then 
        echo -e "\e[1;33m[*] Menginstall Gem Lolcat...\e[0m"
        gem install lolcat
    fi
    
    # --- [FIX] AUTO COOKIES GENERATOR ---
    # Membuat folder data jika belum ada
    if [ ! -d "/sdcard/INTISARI_DATA" ]; then mkdir -p "/sdcard/INTISARI_DATA"; fi
    
    # Cek file cookies, jika kosong atau tidak ada, buat baru dengan Header Netscape
    if [ ! -s "/sdcard/INTISARI_DATA/cookies.txt" ]; then
        echo "# Netscape HTTP Cookie File" > "/sdcard/INTISARI_DATA/cookies.txt"
        echo "# This file was generated by Intisari AutoCut" >> "/sdcard/INTISARI_DATA/cookies.txt"
    fi

    # Install YT-DLP (Engine Download)
    if [ ! -f "$YTDLP_CMD" ]; then
        echo -e "\e[1;33m[*] Mengunduh Engine YouTube (YT-DLP)...\e[0m"
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o "$YTDLP_CMD"
        chmod +x "$YTDLP_CMD"
    fi
    
    # Update YT-DLP jika sudah ada (Silent)
    "$YTDLP_CMD" -U &> /dev/null &
}

# --- [2] FUNGSI UPDATE PINTAR (SMART UPDATE) ---
cek_update_otomatis() {
    # Cek koneksi internet dulu (timeout 3 detik)
    if ! curl -s --head  --request GET https://google.com --max-time 3 | grep "200 OK" > /dev/null; then
        return # Skip jika offline
    fi

    # Ambil manifest dari server
    local manifest_data=$(curl -s --max-time 5 "$LINK_MANIFEST")
    
    # [FIX] Jika manifest kosong/gagal download, hentikan fungsi
    if [ -z "$manifest_data" ]; then return; fi

    # Parsing Data Manifest (DENGAN SAFEGUARD)
    # Mengambil nilai setelah tanda sama dengan (=) dan menghapus karakter return (\r)
    local srv_core=$(echo "$manifest_data" | grep "^CORE=" | cut -d'=' -f2 | tr -d '\r')
    local zip_url=$(echo "$manifest_data" | grep "^ZIP_URL=" | cut -d'=' -f2 | tr -d '\r')

    # [FIX] Cegah Error Matematika: Jika variabel kosong, isi dengan versi saat ini (agar dianggap sama)
    : "${srv_core:=$SYS_VER}"
    
    # Logic Cek Update menggunakan AWK (Support Floating Point)
    # Jika Server > Lokal, maka Update
    local butuh_update=$(awk -v srv="$srv_core" -v loc="$SYS_VER" 'BEGIN {print (srv > loc) ? 1 : 0}')

    if [ "$butuh_update" -eq 1 ]; then
        clear
        echo -e "\e[1;32m[!] UPDATE TERSEDIA: Versi $srv_core (Lokal: $SYS_VER)\e[0m"
        echo -e "\e[1;37m    Sedang mengunduh pembaruan otomatis...\e[0m"
        
        # Download ZIP Update ke folder tmp
        if curl -L "$zip_url" -o "$SCRIPT_DIR/update.zip"; then
            
            # [FIX] SECURITY: CEK INTEGRITAS ZIP SEBELUM EKSTRAK
            if unzip -t "$SCRIPT_DIR/update.zip" >/dev/null 2>&1; then
                echo -e "\e[1;33m[*] Mengekstrak file...\e[0m"
                
                # Unzip dan timpa file lama (-o = overwrite)
                unzip -o "$SCRIPT_DIR/update.zip" -d "$SCRIPT_DIR/" > /dev/null 2>&1
                
                # Hapus file zip
                rm "$SCRIPT_DIR/update.zip"
                
                # Set Permission ulang
                chmod +x "$SCRIPT_DIR/"*.sh
                chmod +x "$SCRIPT_DIR/modules/"*.sh
                
                echo -e "\e[1;32m[V] Update Selesai! Restarting...\e[0m"
                sleep 2
                bash "$SCRIPT_DIR/main.sh"
                exit 0
            else
                echo -e "\e[1;31m[!] File Update Korup! Membatalkan instalasi.\e[0m"
                rm "$SCRIPT_DIR/update.zip"
                # Jangan exit script utama, cukup return agar user bisa pakai versi lama
                return 
            fi
        else
            echo -e "\e[1;31m[!] Gagal mengunduh update. Koneksi buruk.\e[0m"
            sleep 2
        fi
    fi
}

# --- [3] TRIGGER UPDATE MANUAL (OPSIONAL) ---
update_tools() {
    clear
    echo -e "\e[1;34m[*] Mengecek Pembaruan Manual...\e[0m"
    
    # Paksa set variabel srv_core ke nilai tinggi jika ingin tes (debug), 
    # tapi di sini kita pakai logic normal.
    cek_update_otomatis
    
    echo -e "\e[1;32m[V] Sistem Anda sudah yang terbaru ($SYS_VER).\e[0m"
    read -p "Tekan Enter untuk kembali..."
}